# Generated by Django 5.2.17 on 2026-08-28 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=120, verbose_name='نام و نام خانوادگی')),
                ('phone', models.CharField(db_index=True, max_length=20, verbose_name='شماره موبایل')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
            ],
            options={
                'verbose_name': 'بیمار',
                'verbose_name_plural': 'بیماران',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScheduleException',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='تاریخ')),
                ('kind', models.CharField(choices=[('closed', 'تعطیل'), ('custom', 'ساعت کاری خاص')], default='closed', max_length=10, verbose_name='نوع')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='شروع')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='پایان')),
                ('note', models.CharField(blank=True, max_length=250, verbose_name='توضیح')),
            ],
            options={
                'verbose_name': 'استثنای برنامه',
                'verbose_name_plural': 'استثناهای برنامه',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='WeeklySchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.PositiveSmallIntegerField(choices=[(0, 'شنبه'), (1, 'یکشنبه'), (2, 'دوشنبه'), (3, 'سه\u200cشنبه'), (4, 'چهارشنبه'), (5, 'پنجشنبه'), (6, 'جمعه')], verbose_name='روز هفته')),
                ('start_time', models.TimeField(verbose_name='شروع')),
                ('end_time', models.TimeField(verbose_name='پایان')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'برنامه هفتگی',
                'verbose_name_plural': 'برنامه هفتگی',
                'ordering': ['weekday', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, verbose_name='تاریخ')),
                ('start_time', models.TimeField(verbose_name='شروع')),
                ('end_time', models.TimeField(verbose_name='پایان')),
                ('status', models.CharField(choices=[('booked', 'رزرو شده'), ('cancelled', 'لغو شده'), ('completed', 'انجام شده'), ('no_show', 'عدم مراجعه')], default='booked', max_length=12, verbose_name='وضعیت')),
                ('source', models.CharField(choices=[('online', 'رزرو آنلاین'), ('reception', 'ثبت توسط منشی')], default='online', max_length=10, verbose_name='منبع')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ثبت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='appointments.patient', verbose_name='بیمار')),
            ],
            options={
                'verbose_name': 'نوبت',
                'verbose_name_plural': 'نوبت\u200cها',
                'ordering': ['date', 'start_time'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'booked')), fields=('date', 'start_time'), name='unique_active_appointment_slot')],
            },
        ),
    ]
