# Generated by Django 5.2.17 on 2026-08-29 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseStudy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('before_image', models.ImageField(upload_to='cases/', verbose_name='عکس قبل')),
                ('after_image', models.ImageField(upload_to='cases/', verbose_name='عکس بعد')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='کپشن (اختیاری)')),
                ('is_published', models.BooleanField(default=True, verbose_name='نمایش در سایت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ثبت')),
            ],
            options={
                'verbose_name': 'نمونه کار (قبل/بعد)',
                'verbose_name_plural': 'نمونه\u200cکارها (قبل/بعد)',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SiteImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(choices=[('hero', 'تصویر هیرو (پس\u200cزمینه صفحه اول)'), ('doctor', 'عکس دکتر'), ('problem_gum', 'تصویر کارت «بیماری لثه»'), ('problem_implant', 'تصویر کارت «بی\u200cدندانی»')], max_length=20, unique=True, verbose_name='جایگاه تصویر')),
                ('image', models.ImageField(blank=True, null=True, upload_to='site/', verbose_name='تصویر')),
                ('alt_text', models.CharField(blank=True, max_length=200, verbose_name='متن جایگزین (alt)')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
            ],
            options={
                'verbose_name': 'تصویر ثابت سایت',
                'verbose_name_plural': 'تصاویر ثابت سایت',
                'ordering': ['key'],
            },
        ),
    ]
